import { Plan } from "../types";

export const DEFAULT_PLAN: Plan = {
  id: "plan-1",
  name: "Body Control",
  isActive: true,
  goals: [
    {
      id: "goal-1",
      name: "10 clean pull-ups",
      skill: {
        id: "skill-pullups",
        name: "Pull-ups",
        currentStepIndex: 2,
        autoAdvance: {
          threshold: 8,
          sessionsRequired: 3,
          consecutiveCount: 0,
          pendingAdvance: false,
        },
        steps: [
          {
            id: "step-pu-1",
            description: "Dead hang × 30s",
            targetDuration: 30,
            isCompleted: true,
          },
          {
            id: "step-pu-2",
            description: "Scapular pull-ups × 8",
            targetReps: 8,
            isCompleted: true,
          },
          {
            id: "step-pu-3",
            description: "Band-assisted pull-ups × 5",
            targetReps: 5,
            isCompleted: false,
          },
          {
            id: "step-pu-4",
            description: "Negative pull-ups × 5",
            targetReps: 5,
            isCompleted: false,
          },
          {
            id: "step-pu-5",
            description: "Pull-ups × 10",
            targetReps: 10,
            isCompleted: false,
          },
        ],
      },
    },
    {
      id: "goal-2",
      name: "Freestanding handstand",
      skill: {
        id: "skill-handstand",
        name: "Handstand",
        currentStepIndex: 1,
        autoAdvance: {
          threshold: 45,
          sessionsRequired: 3,
          consecutiveCount: 0,
          pendingAdvance: false,
        },
        steps: [
          {
            id: "step-hs-1",
            description: "Wall plank hold × 30s",
            targetDuration: 30,
            isCompleted: true,
          },
          {
            id: "step-hs-2",
            description: "Wall handstand × 20s",
            targetDuration: 20,
            isCompleted: false,
          },
          {
            id: "step-hs-3",
            description: "Wall handstand × 45s",
            targetDuration: 45,
            isCompleted: false,
          },
          {
            id: "step-hs-4",
            description: "Kick-up practice",
            isCompleted: false,
          },
          {
            id: "step-hs-5",
            description: "Freestanding hold × 5s",
            targetDuration: 5,
            isCompleted: false,
          },
        ],
      },
    },
    {
      id: "goal-3",
      name: "Full pistol squat",
      skill: {
        id: "skill-pistol",
        name: "Pistol squat",
        currentStepIndex: 0,
        autoAdvance: null,
        steps: [
          {
            id: "step-ps-1",
            description: "Assisted pistol squat (hold pole)",
            targetReps: 5,
            isCompleted: false,
          },
          {
            id: "step-ps-2",
            description: "Single leg box squat",
            targetReps: 8,
            isCompleted: false,
          },
          {
            id: "step-ps-3",
            description: "Full pistol squat × 5",
            targetReps: 5,
            isCompleted: false,
          },
          {
            id: "step-ps-4",
            description: "Full pistol squat × 10",
            targetReps: 10,
            isCompleted: false,
          },
        ],
      },
    },
  ],
  program: {
    id: "program-1",
    name: "3-day Split",
    workouts: [
      {
        id: "workout-pull-push",
        name: "Pull & Push",
        color: "#BA7517",
        exercises: [
          {
            id: "ex-pu-1",
            name: "Band-assisted pull-ups",
            sets: 4,
            reps: 5,
            restSeconds: 90,
            unit: "reps",
            tagId: "tag-skill",
            skillStepLink: { skillId: "skill-pullups", stepIndex: 2 },
            alternatives: ["Negative pull-ups", "Dead hang × 20s"],
            minReps: 3,
          },
          {
            id: "ex-inverted-row-1",
            name: "Inverted rows",
            sets: 3,
            reps: 10,
            restSeconds: 90,
            unit: "reps",
            tagId: "tag-skill",
            alternatives: ["Australian rows", "TRX rows"],
            minReps: 8,
          },
          {
            id: "ex-dips-1",
            name: "Dips",
            sets: 4,
            restSeconds: 90,
            unit: "reps",
            tagId: "tag-skill",
            alternatives: ["Bench dips", "Negative dips"],
            minReps: 3,
          },
          {
            id: "ex-row-1",
            name: "Dumbbell Row",
            sets: 3,
            reps: 10,
            restSeconds: 60,
            unit: "reps",
            tagId: "tag-weight",
            alternatives: [],
          },
          {
            id: "ex-hollow-1",
            name: "Hollow body hold",
            sets: 3,
            duration: 30,
            restSeconds: 60,
            unit: "seconds",
            tagId: "tag-core",
            alternatives: [],
          },
          {
            id: "ex-pike-lift-1",
            name: "Seated pike lifts",
            sets: 2,
            reps: 10,
            restSeconds: 60,
            unit: "reps",
            tagId: "tag-core",
            alternatives: ["Hollow body hold"],
          },
        ],
      },
      {
        id: "workout-handstand",
        name: "Handstand & Shoulders",
        color: "#185FA5",
        exercises: [
          {
            id: "ex-hs-1",
            name: "Wall handstand hold",
            sets: 4,
            restSeconds: 90,
            unit: "seconds",
            tagId: "tag-skill",
            skillStepLink: { skillId: "skill-handstand", stepIndex: 1 },
            alternatives: ["Pike hold × 30s", "Headstand × 20s"],
            minReps: 10,
          },
          {
            id: "ex-pike-1",
            name: "Pike push-ups",
            sets: 4,
            reps: 8,
            restSeconds: 60,
            unit: "reps",
            tagId: "tag-skill",
            alternatives: ["Elevated pike push-ups"],
          },
          {
            id: "ex-lateral-1",
            name: "Lateral raises",
            sets: 3,
            reps: 15,
            restSeconds: 60,
            unit: "reps",
            tagId: "tag-weight",
            alternatives: [],
          },
        ],
      },
      {
        id: "workout-lower",
        name: "Lower Body",
        color: "#993C1D",
        exercises: [
          {
            id: "ex-pistol-1",
            name: "Assisted pistol squat",
            sets: 3,
            reps: 5,
            restSeconds: 180,
            unit: "reps_per_leg",
            tagId: "tag-skill",
            skillStepLink: { skillId: "skill-pistol", stepIndex: 0 },
            alternatives: ["Single leg box squat", "Single leg box step"],
            minReps: 3,
          },
          {
            id: "ex-lunges-1",
            name: "Dumbbell lunges",
            sets: 3,
            reps: 10,
            restSeconds: 60,
            unit: "reps_per_leg",
            tagId: "tag-weight",
            alternatives: [],
          },
          {
            id: "ex-nordic-1",
            name: "Nordic curl negatives",
            sets: 3,
            reps: 5,
            restSeconds: 90,
            unit: "reps",
            tagId: "tag-skill",
            alternatives: ["Sliding hamstring curl", "Romanian deadlift"],
            minReps: 3,
          },
          {
            id: "ex-calf-1",
            name: "Single-leg calf raises",
            sets: 3,
            reps: 15,
            restSeconds: 60,
            unit: "reps_per_leg",
            tagId: "tag-weight",
            alternatives: [],
          },
          {
            id: "ex-plank-1",
            name: "Plank",
            sets: 3,
            duration: 40,
            restSeconds: 60,
            unit: "seconds",
            tagId: "tag-core",
            alternatives: [],
          },
        ],
      },
    ],
  },
};
